// Service worker for Complete Spanish Review.
//
// Generated by app/build_app.py from this template - do not edit the root
// sw.js directly (same rule as index.html: it's overwritten on every build).
//
// The one rule this file exists to enforce: a real user's browser must NEVER
// get pinned to an old build forever. So the document (the page itself) is
// always fetched from the network first; the cache only serves it when the
// network is genuinely unavailable. Everything else follows from that.

"use strict";

// Bumped automatically on every build (it's a hash of the built index.html),
// so any content or code change ships a byte-different sw.js, which the
// browser detects as an update on its own.
var BUILD_ID = "b39fe2620420";
var CACHE_NAME = "lt-review-" + BUILD_ID;

// ---- KILL SWITCH ----
// If a bad deploy of this file (or of the app it serves) ever needs undoing
// for everyone, edit this one line to `true`, rebuild, and redeploy. Every
// tab that already has this worker installed - and everyone who visits next -
// will unregister it, delete every cache it made, and fall back to plain
// network requests, same as if the PWA layer had never shipped. No other
// file needs to change, and no one needs access to an individual device.
var KILL_SWITCH = false;

var PRECACHE_URLS = [
  "/",
  "/manifest.json",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/icon-maskable-512.png",
  "/icons/apple-touch-icon.png",
  "/icons/favicon-32.png"
];

// The document always lives under one cache key (the app's own scope, i.e.
// "/") regardless of the exact URL it was requested as (with or without a
// trailing query string, "/index.html" vs "/", etc.) - there is only ever
// one page in this app.
function docCacheKey() {
  return new Request(self.registration.scope);
}

self.addEventListener("install", function (event) {
  self.skipWaiting(); // take over immediately on update, don't wait for old tabs to close
  if (KILL_SWITCH) return;
  event.waitUntil(
    caches.open(CACHE_NAME).then(function (cache) {
      return cache.addAll(PRECACHE_URLS).catch(function () {
        // Best-effort: a single missing precache URL shouldn't fail install.
      });
    })
  );
});

self.addEventListener("activate", function (event) {
  event.waitUntil(
    (async function () {
      if (KILL_SWITCH) {
        var keys = await caches.keys();
        await Promise.all(keys.map(function (k) { return caches.delete(k); }));
        await self.registration.unregister();
        var clientsList = await self.clients.matchAll({ type: "window" });
        clientsList.forEach(function (c) { c.navigate(c.url); });
        return;
      }
      // Clean up every cache from a previous build - this is the other half
      // of "never stale": old bytes don't linger on disk once a new build
      // has taken over.
      var keys = await caches.keys();
      await Promise.all(
        keys.filter(function (k) { return k !== CACHE_NAME; })
          .map(function (k) { return caches.delete(k); })
      );
      await self.clients.claim();
    })()
  );
});

self.addEventListener("fetch", function (event) {
  if (KILL_SWITCH) return; // let the browser handle every request as if there were no worker

  var req = event.request;
  if (req.method !== "GET") return;

  var url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // never intercept cross-origin requests

  var isDocument = req.mode === "navigate" ||
    (req.headers.get("accept") || "").indexOf("text/html") !== -1;

  if (isDocument) {
    event.respondWith(networkFirstDocument(req));
    return;
  }
  event.respondWith(networkFirstAsset(req));
});

// Network-first, cache as the offline fallback only - never the other way
// round. A successful fetch always overwrites the cached copy, so the very
// next offline visit already has today's build, not whatever shipped when
// the app was first installed.
function networkFirstDocument(req) {
  return fetch(req).then(function (res) {
    if (res && res.ok) {
      var copy = res.clone();
      caches.open(CACHE_NAME).then(function (cache) { cache.put(docCacheKey(), copy); });
    }
    return res;
  }).catch(function () {
    return caches.match(docCacheKey()).then(function (cached) {
      return cached || caches.match(req);
    });
  });
}

function networkFirstAsset(req) {
  return fetch(req).then(function (res) {
    if (res && res.ok) {
      var copy = res.clone();
      caches.open(CACHE_NAME).then(function (cache) { cache.put(req, copy); });
    }
    return res;
  }).catch(function () {
    return caches.match(req);
  });
}
